diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
user.name=nhom0337LTM
user.email=116172939+nhom0337LTM@users.noreply.github.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.VideoStreamming.url=https://github.com/nhom0337LTM/VideoStreaming.git
remote.VideoStreamming.fetch=+refs/heads/*:refs/remotes/VideoStreamming/*
remote.gitVS.url=https://github.com/nhom0337LTM/VideoStreaming.git
remote.gitVS.fetch=+refs/heads/*:refs/remotes/gitVS/*
remote.gitVideoStreaming.url=https://github.com/nhom0337/VideoStreaming
remote.gitVideoStreaming.fetch=+refs/heads/*:refs/remotes/gitVideoStreaming/*
remote.gitVideoStr.url=https://github.com/nhom0337/VideoStreaming.git
remote.gitVideoStr.fetch=+refs/heads/*:refs/remotes/gitVideoStr/*
remote.gitPushVideo.url=https://github.com/nhom0337LTM/VideoStreaming.git
remote.gitPushVideo.fetch=+refs/heads/*:refs/remotes/gitPushVideo/*
remote.gitProject.url=https://github.com/nhom0337LTM/VideoStreaming.git
remote.gitProject.fetch=+refs/heads/*:refs/remotes/gitProject/*
